services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 64M
    networks:
      - saai-blocks-for-wc_default

networks:
  saai-blocks-for-wc_default:
    external: true
